array_layout = "Block"
array_width = 80
chain_one_line_max = 80
chain_split_single_child = true
condense_wildcard_suffixes = true
fn_args_layout = "Block"
fn_args_paren_newline = false
fn_call_style = "Block"
format_strings = true
generics_indent = "Block"
match_block_trailing_comma = true
reorder_imported_names = true
reorder_imports = true
reorder_imports_in_group = true
space_before_struct_lit_field_colon = false
struct_lit_multiline_style = "ForceMulti"
trailing_comma = "Never"
use_try_shorthand = true
wrap_comments = true
