[package]
name = "nvml-wrapper"
version = "0.1.0"
authors = ["Cldfire"]
description = "A complete, safe, and ergonomic Rust wrapper for the NVIDIA Management Library."
readme = "README.md"
documentation = "https://docs.rs/nvml-wrapper"
repository = "https://github.com/Cldfire/nvml-wrapper"
license = "MIT/Apache-2.0"

keywords = ["nvidia", "gpu", "managment", "monitoring", "hardware"]
categories = ["api-bindings", "hardware-support"]

exclude = [
    "nvml-wrapper-sys/*"
]

[dependencies]
error-chain = "0.10"
bitflags = "0.8"
serde = { version = "1.0", optional = true, features = ["derive"] }
nvml-wrapper-sys = "0.1"
wrapcenum-derive = "0.1"

[features]
default = []
test-local = []
nightly = ["nvml-wrapper-sys/nightly"]
