[package]
name = "nvml"
version = "0.1.0"
authors = ["Cldfire"]

[dependencies]
error-chain = "0.10"
bitflags = "0.8"
nvml-sys = { path = "nvml-sys" }
nvml-derive = { path = "nvml-derive" }

[features]
default = []
test-local = []
nightly = ["nvml-sys/nightly"]
