[package]
name = "nvml"
version = "0.1.0"
authors = ["Cldfire"]

[dependencies]
error-chain = "0.10"
bitflags = "0.8"
serde = { version = "1.0", optional = true, features = ["derive"] }
nvml-sys = { path = "nvml-sys" }
wrapcenum-derive = { path = "../wrapcenum-derive" }

[features]
default = []
test-local = []
nightly = ["nvml-sys/nightly"]
